BEGIN;

DELETE FROM issue_fact
 WHERE source_system = 'DEMO'
   AND source_instance = 'system-test-multi-board-demo'
   AND project_name IN ('2026R3', '2026R4');

INSERT INTO issue_fact (
  id, source_system, source_instance, ingest_channel, source_summary, raw_payload,
  project_id, project_name, issue_id, issue_iid, title, issue_state, issue_type,
  milestone_title, author_name, assignee_name,
  created_at_source, updated_at_source, ods_updated_at, closed_at_source,
  module_name, primary_module_name, module_names, function_name,
  testing_phase, severity_level, severity_alias, priority_level, urgency,
  bug_status, category, reason_category, system_test_label, label_names,
  primary_phase_label, phase_filter_value,
  search_text, search_compact, search_spell, search_initials,
  title_search_text, title_search_compact, title_search_spell, title_search_initials,
  module_search_text, module_search_compact, module_search_spell, module_search_initials,
  milestone_search_text, milestone_search_compact, milestone_search_spell, milestone_search_initials,
  author_search_text, author_search_compact, author_search_spell, author_search_initials,
  assignee_search_text, assignee_search_compact, assignee_search_spell, assignee_search_initials,
  phase_search_text, phase_search_compact, phase_search_spell, phase_search_initials,
  is_excluded, exclusion_reason, is_fixed, delay_issue, delay_reason, delay_cause,
  is_regression, is_crash, is_level1_other, is_illegal, illegal_reason,
  has_response, response_overdue, is_response_delayed, resolve_sla_days, resolve_deadline_at,
  is_resolve_delayed, is_legacy, deleted, fact_refreshed_at, created_at, updated_at
)
VALUES
  (29001, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29001, 301, '登录流程首轮阻塞缺陷', 'opened', 'BUG', '系统测试R3', '张三', '李四', '2026-05-20 09:00:00', '2026-05-27 10:00:00', now(), null, '认证', '认证', '认证,登录', '登录', '系统测试 第一轮', 'LEVEL1', '一级缺陷', 'P1', '高', '待修复', '功能', '需求理解偏差', '系统测试 第一轮', '申请延期,系统测试', '系统测试 第一轮', '系统测试', '登录流程首轮阻塞缺陷 2026R3 张三 认证 登录', '登录流程首轮阻塞缺陷2026R3张三认证登录', '', '', '登录流程首轮阻塞缺陷', '登录流程首轮阻塞缺陷', '', '', '认证 登录', '认证登录', '', '', '系统测试R3', '系统测试R3', '', '', '张三', '张三', '', '', '李四', '李四', '', '', '系统测试 第一轮', '系统测试第一轮', '', '', false, '', false, true, '需求澄清未完成', '需求审批滞后', true, false, false, false, '', true, true, true, 7, '2026-05-28 18:00:00', true, false, false, now(), now(), now()),
  (29002, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29002, 302, '渲染结果回退问题', 'closed', 'BUG', '系统测试R3', '李四', '王五', '2026-05-20 10:00:00', '2026-05-27 11:00:00', now(), '2026-05-27 18:30:00', '渲染', '渲染', '渲染,导出', '渲染出图', '系统测试 第一轮', 'LEVEL1', '一级缺陷', 'P1', '高', '已关闭', '功能', '编码逻辑错误', '系统测试 第一轮', '复测未通过,系统测试', '系统测试 第一轮', '系统测试', '渲染结果回退问题 2026R3 李四 渲染 导出', '渲染结果回退问题2026R3李四渲染导出', '', '', '渲染结果回退问题', '渲染结果回退问题', '', '', '渲染 导出', '渲染导出', '', '', '系统测试R3', '系统测试R3', '', '', '李四', '李四', '', '', '王五', '王五', '', '', '系统测试 第一轮', '系统测试第一轮', '', '', false, '', true, false, '', '', true, false, false, false, '', true, false, false, 3, '2026-05-27 12:00:00', false, false, false, now(), now(), now()),
  (29003, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29003, 303, '安装包启动崩溃', 'opened', 'BUG', '系统测试R3', '王五', '赵六', '2026-05-21 09:30:00', '2026-05-27 12:30:00', now(), null, '安装器', '安装器', '安装器,启动器', '安装启动', '系统测试 第二轮', 'LEVEL1', '一级缺陷', 'P1', '高', '处理中', '功能', '环境部署问题', '系统测试 第二轮', '申请延期,系统测试', '系统测试 第二轮', '系统测试', '安装包启动崩溃 2026R3 王五 安装器 启动器', '安装包启动崩溃2026R3王五安装器启动器', '', '', '安装包启动崩溃', '安装包启动崩溃', '', '', '安装器 启动器', '安装器启动器', '', '', '系统测试R3', '系统测试R3', '', '', '王五', '王五', '', '', '赵六', '赵六', '', '', '系统测试 第二轮', '系统测试第二轮', '', '', false, '', false, true, '部署脚本未准备完成', '环境资源冲突', false, true, false, false, '', false, true, true, 5, '2026-05-29 12:00:00', true, false, false, now(), now(), now()),
  (29004, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29004, 304, 'BOM计算规则需调整', 'closed', 'BUG', '系统测试R3', '赵六', '钱七', '2026-05-21 14:00:00', '2026-05-27 14:10:00', now(), '2026-05-27 19:00:00', 'BOM', 'BOM', 'BOM,规则引擎', '规则计算', '系统测试 第二轮', 'LEVEL2', '二级缺陷', 'P2', '中', '已验证', '功能', '新增需求', '系统测试 第二轮', '系统测试', '系统测试 第二轮', '系统测试', 'BOM计算规则需调整 2026R3 赵六 BOM 规则引擎', 'BOM计算规则需调整2026R3赵六BOM规则引擎', '', '', 'BOM计算规则需调整', 'BOM计算规则需调整', '', '', 'BOM 规则引擎', 'BOM规则引擎', '', '', '系统测试R3', '系统测试R3', '', '', '赵六', '赵六', '', '', '钱七', '钱七', '', '', '系统测试 第二轮', '系统测试第二轮', '', '', false, '', true, false, '', '', false, false, false, false, '', true, false, false, 4, '2026-05-28 10:00:00', false, false, false, now(), now(), now()),
  (29005, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29005, 305, '装配视图标注错位', 'opened', 'BUG', '系统测试R3', '钱七', '孙八', '2026-05-22 09:15:00', '2026-05-27 15:20:00', now(), null, '装配', '装配', '装配,标注', '视图标注', '回归测试', 'LEVEL2', '二级缺陷', 'P2', '中', '待回归', '功能', '编码逻辑错误', '回归测试', '复测未通过,回归测试', '回归测试', '回归测试', '装配视图标注错位 2026R3 钱七 装配 标注', '装配视图标注错位2026R3钱七装配标注', '', '', '装配视图标注错位', '装配视图标注错位', '', '', '装配 标注', '装配标注', '', '', '系统测试R3', '系统测试R3', '', '', '钱七', '钱七', '', '', '孙八', '孙八', '', '', '回归测试', '回归测试', '', '', false, '', false, true, '回归窗口不足', '排期冲突', false, false, false, false, '', true, true, true, 6, '2026-05-30 12:00:00', true, false, false, now(), now(), now()),
  (29006, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29006, 306, '工程图导出精度异常', 'opened', 'BUG', '系统测试R3', '孙八', '周九', '2026-05-22 11:00:00', '2026-05-27 16:00:00', now(), null, '工程图', '工程图', '工程图,导出', 'PDF导出', '回归测试', 'LEVEL3', '三级缺陷', 'P3', '低', '处理中', '体验', '算法机制不支持', '回归测试', '系统测试', '回归测试', '回归测试', '工程图导出精度异常 2026R3 孙八 工程图 导出', '工程图导出精度异常2026R3孙八工程图导出', '', '', '工程图导出精度异常', '工程图导出精度异常', '', '', '工程图 导出', '工程图导出', '', '', '系统测试R3', '系统测试R3', '', '', '孙八', '孙八', '', '', '周九', '周九', '', '', '回归测试', '回归测试', '', '', false, '', false, true, '外部算法包不兼容', '第三方依赖升级', false, false, false, false, '', true, false, false, 8, '2026-06-01 12:00:00', false, false, false, now(), now(), now()),
  (29007, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202603, '2026R3', 29007, 307, '报表筛选文案建议优化', 'closed', 'BUG', '系统测试R3', '周九', '吴十', '2026-05-23 08:40:00', '2026-05-27 16:40:00', now(), '2026-05-27 17:10:00', '报表', '报表', '报表,筛选', '筛选器', '回归测试', 'SUGGESTION', '建议类', 'P3', '低', '已关闭', '体验', '其他原因', '回归测试', '回归测试', '回归测试', '回归测试', '报表筛选文案建议优化 2026R3 周九 报表 筛选', '报表筛选文案建议优化2026R3周九报表筛选', '', '', '报表筛选文案建议优化', '报表筛选文案建议优化', '', '', '报表 筛选', '报表筛选', '', '', '系统测试R3', '系统测试R3', '', '', '周九', '周九', '', '', '吴十', '吴十', '', '', '回归测试', '回归测试', '', '', false, '', true, false, '', '', false, false, false, false, '', true, false, false, 2, '2026-05-27 18:00:00', false, false, false, now(), now(), now()),
  (29008, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202604, '2026R4', 29008, 401, '权限配置导致数据看板空白', 'opened', 'BUG', '系统测试R4', '吴十', '冯二', '2026-05-24 09:10:00', '2026-05-27 17:10:00', now(), null, '权限', '权限', '权限,数据看板', '权限开关', '系统测试 第一轮', 'LEVEL1', '一级缺陷', 'P1', '高', '处理中', '功能', '需求理解偏差', '系统测试 第一轮', '申请延期,系统测试', '系统测试 第一轮', '系统测试', '权限配置导致数据看板空白 2026R4 吴十 权限 数据看板', '权限配置导致数据看板空白2026R4吴十权限数据看板', '', '', '权限配置导致数据看板空白', '权限配置导致数据看板空白', '', '', '权限 数据看板', '权限数据看板', '', '', '系统测试R4', '系统测试R4', '', '', '吴十', '吴十', '', '', '冯二', '冯二', '', '', '系统测试 第一轮', '系统测试第一轮', '', '', false, '', false, true, '权限方案待确认', '跨团队依赖', true, false, false, false, '', false, true, true, 7, '2026-05-30 09:00:00', true, false, false, now(), now(), now()),
  (29009, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202604, '2026R4', 29009, 402, '消息中心偶发闪退', 'closed', 'BUG', '系统测试R4', '冯二', '陈三', '2026-05-24 10:20:00', '2026-05-27 18:00:00', now(), '2026-05-27 20:00:00', '消息中心', '消息中心', '消息中心,通知', '通知列表', '系统测试 第一轮', 'LEVEL1', '一级缺陷', 'P1', '高', '已关闭', '功能', '编码逻辑错误', '系统测试 第一轮', '系统测试', '系统测试 第一轮', '系统测试', '消息中心偶发闪退 2026R4 冯二 消息中心 通知', '消息中心偶发闪退2026R4冯二消息中心通知', '', '', '消息中心偶发闪退', '消息中心偶发闪退', '', '', '消息中心 通知', '消息中心通知', '', '', '系统测试R4', '系统测试R4', '', '', '冯二', '冯二', '', '', '陈三', '陈三', '', '', '系统测试 第一轮', '系统测试第一轮', '', '', false, '', true, false, '', '', false, true, false, false, '', true, false, false, 3, '2026-05-28 11:00:00', false, false, false, now(), now(), now()),
  (29010, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202604, '2026R4', 29010, 403, '同步任务卡死在队列中', 'opened', 'BUG', '系统测试R4', '陈三', '蒋四', '2026-05-25 08:30:00', '2026-05-27 18:40:00', now(), null, '同步服务', '同步服务', '同步服务,队列', '任务同步', '系统测试 第二轮', 'LEVEL2', '二级缺陷', 'P2', '中', '处理中', '功能', '环境部署问题', '系统测试 第二轮', '申请延期,系统测试', '系统测试 第二轮', '系统测试', '同步任务卡死在队列中 2026R4 陈三 同步服务 队列', '同步任务卡死在队列中2026R4陈三同步服务队列', '', '', '同步任务卡死在队列中', '同步任务卡死在队列中', '', '', '同步服务 队列', '同步服务队列', '', '', '系统测试R4', '系统测试R4', '', '', '陈三', '陈三', '', '', '蒋四', '蒋四', '', '', '系统测试 第二轮', '系统测试第二轮', '', '', false, '', false, true, '测试环境消息堆积', '环境资源冲突', false, false, false, false, '', false, true, true, 5, '2026-05-31 18:00:00', true, false, false, now(), now(), now()),
  (29011, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202604, '2026R4', 29011, 404, '移动端旋转后按钮遮挡', 'opened', 'BUG', '系统测试R4', '蒋四', '韩七', '2026-05-25 10:00:00', '2026-05-27 19:10:00', now(), null, '移动端', '移动端', '移动端,布局', '横竖屏切换', '系统测试 第二轮', 'LEVEL3', '三级缺陷', 'P3', '低', '待修复', '体验', '其他原因', '系统测试 第二轮', '回归测试', '系统测试 第二轮', '系统测试', '移动端旋转后按钮遮挡 2026R4 蒋四 移动端 布局', '移动端旋转后按钮遮挡2026R4蒋四移动端布局', '', '', '移动端旋转后按钮遮挡', '移动端旋转后按钮遮挡', '', '', '移动端 布局', '移动端布局', '', '', '系统测试R4', '系统测试R4', '', '', '蒋四', '蒋四', '', '', '韩七', '韩七', '', '', '系统测试 第二轮', '系统测试第二轮', '', '', false, '', false, false, '', '', false, false, false, false, '', true, false, false, 4, '2026-05-31 12:00:00', false, false, false, now(), now(), now()),
  (29012, 'DEMO', 'system-test-multi-board-demo', 'MANUAL', 'system-test-multi-board demo', '{}', 202604, '2026R4', 29012, 405, '导出中心提示语建议补充', 'closed', 'BUG', '系统测试R4', '韩七', '张三', '2026-05-25 14:00:00', '2026-05-27 19:30:00', now(), '2026-05-27 20:10:00', '导出中心', '导出中心', '导出中心,交互', '导出任务', '回归测试', 'SUGGESTION', '建议类', 'P3', '低', '已关闭', '体验', '新增需求', '回归测试', '回归测试', '回归测试', '回归测试', '导出中心提示语建议补充 2026R4 韩七 导出中心 交互', '导出中心提示语建议补充2026R4韩七导出中心交互', '', '', '导出中心提示语建议补充', '导出中心提示语建议补充', '', '', '导出中心 交互', '导出中心交互', '', '', '系统测试R4', '系统测试R4', '', '', '韩七', '韩七', '', '', '张三', '张三', '', '', '回归测试', '回归测试', '', '', false, '', true, false, '', '', false, false, false, false, '', true, false, false, 2, '2026-05-28 12:00:00', false, false, false, now(), now(), now());

COMMIT;
