delete from merge_request_fact
 where source_instance in ('cc', 'dgm');

insert into merge_request_fact (
    source_system,
    source_instance,
    ingest_channel,
    source_summary,
    raw_payload,
    project_id,
    project_name,
    repository_name,
    merge_request_id,
    merge_request_iid,
    title,
    merge_request_state,
    target_branch,
    source_branch,
    author_name,
    merge_user_name,
    owner_name,
    reviewer_names,
    assignee_names,
    module_name,
    label_names,
    created_at_source,
    updated_at_source,
    ods_updated_at,
    merged_at_source,
    review_status,
    review_duration_minutes,
    comment_rate,
    comment_rate_source,
    defect_count,
    defect_count_source,
    scan_status,
    scan_bug_count,
    added_lines,
    deleted,
    fact_refreshed_at,
    created_at,
    updated_at
)
select
    source_system,
    'cc' as source_instance,
    ingest_channel,
    coalesce(source_summary, 'GitLab merge request aggregate') || ' / CC local demo data',
    raw_payload,
    project_id,
    project_name,
    repository_name,
    merge_request_id,
    merge_request_iid,
    title,
    merge_request_state,
    target_branch,
    source_branch,
    author_name,
    merge_user_name,
    coalesce(nullif(owner_name, ''), 'CC Owner'),
    reviewer_names,
    assignee_names,
    coalesce(nullif(module_name, ''), case when merge_request_iid % 2 = 0 then 'Payment Center' else 'Order Service' end),
    label_names,
    created_at_source,
    updated_at_source,
    ods_updated_at,
    merged_at_source,
    case when review_status = 'PENDING' then 'COMPLETED' else coalesce(review_status, 'COMPLETED') end,
    coalesce(review_duration_minutes, 12),
    round((coalesce(comment_rate, 18.50) + 1.50)::numeric, 2),
    coalesce(nullif(comment_rate_source, ''), 'CC_TOOL'),
    coalesce(defect_count, 0) + 1,
    coalesce(nullif(defect_count_source, ''), 'CC_ROBOT'),
    scan_status,
    scan_bug_count,
    coalesce(added_lines, 48) + 10,
    deleted,
    fact_refreshed_at,
    created_at,
    updated_at
from merge_request_fact
where source_instance = 'default'
  and deleted = false;

insert into merge_request_fact (
    source_system,
    source_instance,
    ingest_channel,
    source_summary,
    raw_payload,
    project_id,
    project_name,
    repository_name,
    merge_request_id,
    merge_request_iid,
    title,
    merge_request_state,
    target_branch,
    source_branch,
    author_name,
    merge_user_name,
    owner_name,
    reviewer_names,
    assignee_names,
    module_name,
    label_names,
    created_at_source,
    updated_at_source,
    ods_updated_at,
    merged_at_source,
    review_status,
    review_duration_minutes,
    comment_rate,
    comment_rate_source,
    defect_count,
    defect_count_source,
    scan_status,
    scan_bug_count,
    added_lines,
    deleted,
    fact_refreshed_at,
    created_at,
    updated_at
)
select
    source_system,
    'dgm' as source_instance,
    ingest_channel,
    coalesce(source_summary, 'GitLab merge request aggregate') || ' / DGM local demo data',
    raw_payload,
    project_id,
    project_name,
    repository_name,
    merge_request_id,
    merge_request_iid,
    title,
    merge_request_state,
    target_branch,
    source_branch,
    author_name,
    merge_user_name,
    coalesce(nullif(owner_name, ''), 'DGM Owner'),
    reviewer_names,
    assignee_names,
    coalesce(nullif(module_name, ''), case when merge_request_iid % 2 = 0 then 'Assembly Modeling' else 'Collaboration Hub' end),
    label_names,
    created_at_source,
    updated_at_source,
    ods_updated_at,
    merged_at_source,
    coalesce(review_status, 'PENDING'),
    coalesce(review_duration_minutes, 18) + 6,
    round(greatest(coalesce(comment_rate, 14.20) - 2.40, 0)::numeric, 2),
    coalesce(nullif(comment_rate_source, ''), 'DGM_TOOL'),
    coalesce(defect_count, 0) + 2,
    coalesce(nullif(defect_count_source, ''), 'DGM_ROBOT'),
    scan_status,
    scan_bug_count,
    coalesce(added_lines, 52) + 24,
    deleted,
    fact_refreshed_at,
    created_at,
    updated_at
from merge_request_fact
where source_instance = 'default'
  and deleted = false;
